### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by EnderCraft202** [help-chat/DeluxeMenus#3]
Good plugin, I have a question as I do to execute a command from console for a user, example that the console executes a command and gives an object to a user

**Comment by Andre601** [comment]
Hey.

You simply use the `[console]` prefix in the `left_click`, `right_click`, `open` or `deny_command`
You can find more information on the [left/right click commands section](https://github.com/help-chat/DeluxeMenus/wiki/Item#leftright-click-commands) of the [item](https://github.com/help-chat/DeluxeMenus/wiki/Item) wiki page.
