### ISSUE TITLE
Handling player input

### ISSUE THREAD

**Issue by Jose-Paulo-FaD** [help-chat/DeluxeMenus#6]
**Problem:**
Using the [player] tag you cannot let players execute commands that require inputs (e. g. /tpa "PlayerNameHere").

**Possible Solution:**
Add a special tag called `input` with a parameter of msg (`<input=<msg>>`) and a placeholder `%input%` to go with it.

When a click command containing this tag is executed, the `msg` is sent to the player asking for his input and his chat is open. The player them types the required input into the chat and presses enter. His chat input is them pasted in the location of the `%input%` placeholder and the click comand continues as normal.

**Example:**
A GUI item has the following click cofiguration:
```
left_click_commands:
    - '[player] tpa %input%<input="Type the name of the player you want to teleport to:">'
````
When the command is executed, it has the special input tag, so the player input is done first.
`Type the name of the player you want to teleport to:` is printed in the player chat and his chat is open.
The player types `RandomName` in the chat and presses enter.
The `%input%` placeholder is replaced by `RandomName`
The `[player]` tag executes the command `tpa RandomName`

**Comment by Andre601** [comment]
[CommandPrompter]: https://www.spigotmc.org/resources/commandprompter.47772/
[update]: https://www.spigotmc.org/resources/deluxemenus.11734/update?update=224731

In my opinion is that a lot for just a GUI plugin..,

Also DeluxeMenus already supports plugins like [CommandPrompter] which do exactly what you want.
See [this update here][update] for information about how to use.

**Comment by Jose-Paulo-FaD** [comment]
Thanks for the recommendation Andre. Great job on DeluxeMenus
