### ISSUE TITLE
Apostrophes removed on reload

### ISSUE THREAD

**Issue by ReimannMC** [help-chat/DeluxeMenus#7]
Hi there,

I'm using DeluxeMenus 1.10.5
edit:
Server: Spigot-1.8.8.jar
Software: WinSCP

After a few hours of setting up a prestige system, I've come to the conclusion that the config for some reason removes the ' ' (apostrophes) from view_requirement type: '<='

The config included below shows you the config of an item thats supposed to be an info tool for the player. This book shows whether a player has sufficient funds/askyblock island levels to prestige or not.
Because there are multiple options whether a player can/cannot prestige, it's done with multiple configurations for the one item.

https://paste.helpch.at/ayinayaxif.bash

Note that this is the config after performing /dm reload and refreshing the config file.

For some reason, the apostrophes on the '>=' never get removed, but from '<=' they are always removed, not only in the example above, in all other prestige's too.
(I haven't tested it with any other system, just this prestige system)

EDIT 22:03:
The config also removes apostrophes on this symbol: < (input < output)

I have no idea if it's something I'm doing wrong or it's a bug.

Thanks ahead,

**Comment by ReimannMC** [comment]
Bump

Issue still present :(

**Comment by Funny-cube** [comment]
To get support with the plugin please see our discord:
https://helpch.at/discord
This GitHub is only used for holding resources.
